/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BetaalOpdracht { 
    vanIban: string;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    bedrag: string;
    naamOntvanger: string;
    ibanOntvanger: string;
    omschrijving?: string;
    betalingskenmerk?: string;
    extraOmschrijving?: string;
}

