/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Boekingsbevestiging { 
    overboekingId: string;
    datum: string;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    bedrag: string;
    /**
     * Saldo van de van-rekening na de boeking
     */
    saldo: string;
}

