/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RekeninghouderSamenvatting { 
    id: string;
    naam: string;
    betaalrekening?: string;
    spaarrekening?: string;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    saldoBetaal?: string;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    saldoSpaar?: string;
}

