/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RekeningSoort } from './rekening-soort';


export interface RekeningDetail { 
    iban: string;
    soort: RekeningSoort;
    rekeninghouder: string;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    saldo: string;
    simulatiedatum: string;
    /**
     * Spaarrekening - opgebouwde, nog niet bijgeschreven rente deze maand
     */
    lopendeRente?: string;
    rentepercentage?: string;
    /**
     * De andere rekening van dezelfde klant (voor Inleggen/Opnemen)
     */
    gekoppeldeRekening?: string;
    /**
     * true voor de beheerder - Betalen, Inleggen en Opnemen verbergen
     */
    alleenLezen: boolean;
}



