/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RekeningSamenvatting } from './rekening-samenvatting';


export interface RekeningOverzicht { 
    simulatiedatum: string;
    rekeninghouder?: string;
    rekeningen: Array<RekeningSamenvatting>;
}

