/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RekeningSoort } from './rekening-soort';


export interface RekeningSamenvatting { 
    iban: string;
    soort: RekeningSoort;
    /**
     * Bedrag in euro\'s met maximaal 2 decimalen; punt als decimaalteken
     */
    saldo: string;
}



