/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Simulatiedatum { 
    datum: string;
    vanaf: string;
    tot: string;
    /**
     * false als de datum de systeemdatum volgt
     */
    ingesteld: boolean;
}

