/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimulatiedatumWijziging { 
    /**
     * Leeg = terug naar de systeemdatum
     */
    datum?: string;
}

