/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum TransactieType {

    ONLINE_BANKIEREN = 'ONLINE_BANKIEREN',

    IDEAL_WERO = 'IDEAL_WERO',

    BETAALAUTOMAAT = 'BETAALAUTOMAAT',

    INCASSO = 'INCASSO',

    GELDAUTOMAAT = 'GELDAUTOMAAT',

    OVERSCHRIJVING = 'OVERSCHRIJVING',

    VERZAMELBETALING = 'VERZAMELBETALING',

    INLEG = 'INLEG',

    OPNAME = 'OPNAME',

    RENTE = 'RENTE'
}

