/**
 * BankSim API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transactie } from './transactie';


export interface TransactiePagina { 
    items: Array<Transactie>;
    /**
     * Leeg als er niets meer is
     */
    nextCursor?: string;
}

